const sources = {
    'Alabama': 'https://alabama.travel/my-trip/staying-safe/covid-19',
    'Alaska': 'https://covid19.alaska.gov/travelers/',
    'Arizona': 'https://tourism.az.gov/covid-19-updates-2/',
    'Arkansas': 'https://www.arkansas.com/travel-advisory/covid-19',
    'California': 'https://www.visitcalifornia.com/latest-covid-19-coronavirus/',
    'Colorado': 'https://covid19.colorado.gov/travel',
    'Delaware': 'https://www.visitdelaware.com/industry/covid-19-in-delaware/', 
    'Florida': 'https://floridahealthcovid19.gov/travelers/',
    'Georgia': 'https://dph.georgia.gov/covid-19-travel',
    'Hawaii': 'https://www.hawaiitourismauthority.org/covid-19-updates/traveling-to-hawaii/',
    'Idaho': 'https://visitidaho.org/covid-19-travel-alert/',
    'Illinois': 'https://www.chicago.gov/city/en/sites/covid-19/home/emergency-travel-order.html',
    'Indiana': 'https://www.coronavirus.in.gov/',
    'Iowa': 'https://www.traveliowa.com/aspx/general/dynamicpage.aspx?id=204',
    'Kansas': 'https://www.coronavirus.kdheks.gov/175/Travel-Exposure-Related-Isolation-Quaran',
    'Kentucky': 'https://govstatus.egov.com/kycovid19',
    'Louisiana': 'https://louisianatravelassociation.org/covid-19-resources',
    'Maine': 'https://www.maine.gov/covid19/restartingmaine/keepmainehealthy',
    'Maryland': 'https://www.visitmaryland.org/article/travel-alerts',
    'Massachusetts': 'https://www.mass.gov/info-details/covid-19-travel-order',
    'Michigan': 'https://www.michigan.gov/coronavirus/',
    'Minnesota': 'https://www.exploreminnesota.com/info/coronavirus-covid-19-information',
    'Mississippi': 'https://visitmississippi.org/covid-19-travel-alert/',
    'Missouri': 'https://www.visitmo.com/travel-updates',
    'Montana': 'https://www.visitmt.com/travel-alerts.html',
    'Nebraska': 'http://dhhs.ne.gov/Pages/COVID-19-Traveler-Recommendations.aspx',
    'Nevada': 'https://nvhealthresponse.nv.gov/info/travelers-visitors/',
    'New Hampshire': 'https://www.covidguidance.nh.gov/out-state-visitors',
    'New Jersey': 'https://covid19.nj.gov/faqs/nj-information/travel-and-transportation/which-states-are-on-the-travel-advisory-list-are-there-travel-restrictions-to-or-from-new-jersey',
    'New Mexico': 'https://www.newmexico.org/industry/rapid-response-covid-19/covid-19-impact-faq/',
    'New York': 'https://coronavirus.health.ny.gov/covid-19-travel-advisory', 
    'North Carolina': 'https://www.nc.gov/covid-19/covid-19-travel-resources',
    'North Dakokta': 'https://www.health.nd.gov/diseases-conditions/coronavirus/travel-guidance',
    'Ohio':'https://coronavirus.ohio.gov/wps/portal/gov/covid-19/families-and-individuals/COVID-19-Travel-Advisory/COVID-19-Travel-Advisory',
    'Oklahoma':'https://coronavirus.health.ok.gov/travel',
    'Oregon': 'https://traveloregon.com/travel-alerts/',
    'Pennsylvania': 'https://www.health.pa.gov/topics/disease/coronavirus/Pages/Travelers.aspx',
    'Rhode Island': 'https://health.ri.gov/covid/travel/',
    'South Carolina': 'https://scdhec.gov/covid19/resources-community-covid-19/travelers-covid-19',
    'South Dakota': 'https://www.travelsouthdakota.com/coronavirus-covid-19',
    'Tennessee': 'https://www.tnvacation.com/travel-safe',
    'Texas': 'https://gov.texas.gov/travel-texas/page/covid19',
    'Utah': 'https://www.visitutah.com/plan-your-trip/covid-19',
    'Vermont': 'https://www.healthvermont.gov/covid-19/travel-quarantine',
    'Virginia':'https://www.vdh.virginia.gov/coronavirus/frequently-asked-questions/u-s-travelers/',
    'Washington D.C.': 'https://washington.org/dc-information/coronavirus-travel-update-washington-dc',
    'Washington': 'https://coronavirus.wa.gov/travelers-commuters#:~:text=On%20Nov.%2013%2C%202020%2C,for%2014%20days%20after%20arrival.&text=Maintain%20a%20distance%20of%20six,not%20in%20your%20travel%20party.',
    'West Virginia':'https://wvtourism.com/travel-responsibly/',
    'Wisconson':'https://www.dhs.wisconsin.gov/covid-19/travel.htm',
    'Wyoming':'https://health.wyo.gov/publichealth/infectious-disease-epidemiology-unit/disease/novel-coronavirus/covid-19-orders-and-guidance/'
}