---
name: Update Covid Data

on:
  schedule:
    - cron: '0 7,17 * * *'

jobs:
  update:
    name: Update Data
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies and write csv
      run: |
        npm i
        npm run updateData
    - name: Auto update data
      run: git add


...